# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GrpcUtil.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpcclient.google.rpc import status_pb2 as google_dot_rpc_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='GrpcUtil.proto',
  package='util.grpcutil',
  syntax='proto3',
  serialized_options=b'\n\rutil.grpcutilB\010grpcutilP\001Z<gitlab.pri.ibanyu.com/middleware/util/idl/grpc/util/grpcutil',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eGrpcUtil.proto\x12\rutil.grpcutil\x1a\x17google/rpc/status.proto\"H\n\x07\x45rrInfo\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\"\n\x06status\x18\x03 \x01(\x0b\x32\x12.google.rpc.StatusBY\n\rutil.grpcutilB\x08grpcutilP\x01Z<gitlab.pri.ibanyu.com/middleware/util/idl/grpc/util/grpcutilb\x06proto3'
  ,
  dependencies=[google_dot_rpc_dot_status__pb2.DESCRIPTOR,])




_ERRINFO = _descriptor.Descriptor(
  name='ErrInfo',
  full_name='util.grpcutil.ErrInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='util.grpcutil.ErrInfo.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='util.grpcutil.ErrInfo.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='util.grpcutil.ErrInfo.status', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=130,
)

_ERRINFO.fields_by_name['status'].message_type = google_dot_rpc_dot_status__pb2._STATUS
DESCRIPTOR.message_types_by_name['ErrInfo'] = _ERRINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ErrInfo = _reflection.GeneratedProtocolMessageType('ErrInfo', (_message.Message,), {
  'DESCRIPTOR' : _ERRINFO,
  '__module__' : 'GrpcUtil_pb2'
  # @@protoc_insertion_point(class_scope:util.grpcutil.ErrInfo)
  })
_sym_db.RegisterMessage(ErrInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
